
import React from 'react';

const COMMUNITY = [
    { votes: 142, text: "I used the STAR method - Situation, Task, Action, Result. This kept my answer focused and concrete." },
    { votes: 98, text: "I connected my experience directly to the job requirements, showing relevance to what they need." },
];

const safeString = (val) => {
    if (!val) return null;
    if (typeof val === 'string') return val;
    if (typeof val === 'object') {
        if (val.improved) return val.improved;
        if (val.text) return val.text;
        return JSON.stringify(val);
    }
    return String(val);
};

const safeArray = (val) => {
    if (Array.isArray(val)) return val.map(item => safeString(item) || item);
    return [];
};

// Generate PDF report
const downloadPDF = (data, question) => {
    const transcript = safeString(data.transcript) || "Response recorded";
    const vm = data.voice_metrics || {};
    const vis = data.vision_metrics || {};
    const fb = data.feedback || {};
    const an = data.analysis || {};

    const score = typeof fb.score === 'number' ? fb.score : 75;
    const strengths = safeArray(fb.strengths);
    const improvements = safeArray(fb.improvements);

    const content = `
INTERVIEW ANALYSIS REPORT
========================

QUESTION:
${question}

YOUR RESPONSE:
${transcript}

PERFORMANCE SCORE: ${score}/100

METRICS:
- Speaking Pace: ${vm.pace_wpm || 0} WPM
- Word Count: ${vm.word_count || 0}
- Duration: ${Math.round(vm.duration_seconds || 0)} seconds
- Filler Words: ${vm.total_fillers || 0}
- Pauses: ${vm.pause_count || 0}

VOICE ANALYSIS:
- Confidence: ${an.confidence_level || 'Medium'}
- Tone: ${an.tone || 'Professional'}
- Energy: ${an.energy || 'Moderate'}
- Clarity: ${an.clarity || 'Clear'}

VISUAL ANALYSIS:
- Eye Contact: ${vis.looking_away_frequency || 'Good'}
- Confidence: ${vis.confidence_visual || 'Medium'}
- Interest Level: ${vis.interest_level || 'Engaged'}
- Fidgeting: ${vis.fidgeting || 'Minimal'}

STRENGTHS:
${strengths.map(s => `• ${s}`).join('\n') || '• Completed response'}

AREAS TO IMPROVE:
${improvements.map(s => `• ${s}`).join('\n') || '• Add more detail'}

${fb.content_feedback ? `DETAILED FEEDBACK:\n${fb.content_feedback}` : ''}

${fb.follow_up_question ? `\nLIKELY FOLLOW-UP QUESTION:\n"${fb.follow_up_question}"` : ''}

---
Generated by AI Interview Coach
  `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'interview_report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

const AnalysisDashboard = ({ data = {}, onNext, isLastQuestion, question }) => {
    const transcript = safeString(data.transcript) || "Response recorded";
    const vm = data.voice_metrics || {};
    const vis = data.vision_metrics || {};
    const fb = data.feedback || {};
    const an = data.analysis || {};

    const score = typeof fb.score === 'number' ? fb.score : 75;
    const strengths = safeArray(fb.strengths);
    const improvements = safeArray(fb.improvements);

    if (strengths.length === 0) strengths.push("Completed response");
    if (improvements.length === 0) improvements.push("Add more detail");

    let suggestion = null;
    if (fb.improved_answer_suggestion) {
        if (typeof fb.improved_answer_suggestion === 'string') {
            suggestion = fb.improved_answer_suggestion;
        } else if (typeof fb.improved_answer_suggestion === 'object') {
            suggestion = fb.improved_answer_suggestion.improved || fb.improved_answer_suggestion.text || null;
        }
    }

    const followUp = safeString(fb.follow_up_question);

    return (
        <div className="dashboard fade-in">
            {/* Score */}
            <div className="score-card">
                <div>
                    <div className="score-label">Performance Score</div>
                    <div className="score-sublabel">Based on content & delivery</div>
                </div>
                <div className="score-value">{score}</div>
            </div>

            {/* Transcript */}
            <div className="feedback-section">
                <div className="feedback-title">📝 What You Said</div>
                <div style={{ background: '#f9fafb', padding: '1rem', borderRadius: '8px', lineHeight: '1.8', color: '#374151' }}>
                    {transcript}
                </div>
            </div>

            {/* Metrics */}
            <div className="metrics-grid">
                <MetricCard label="Pace" value={`${vm.pace_wpm || 0} WPM`} hint={vm.pace_wpm > 160 ? 'Fast' : vm.pace_wpm < 100 ? 'Slow' : 'Good'} />
                <MetricCard label="Filler Words" value={vm.total_fillers || 0} hint={Object.entries(vm.filler_words || {}).slice(0, 2).map(([w, c]) => `${w}:${c}`).join(' ') || 'None'} />
                <MetricCard label="Pauses" value={vm.pause_count || 0} hint="Hesitations" />
                <MetricCard label="Duration" value={`${Math.round(vm.duration_seconds || 0)}s`} hint={`${vm.word_count || 0} words`} />
            </div>

            {/* Voice & Visual Analysis */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div className="feedback-section">
                    <div className="feedback-title">🎤 Voice</div>
                    <AnalysisRow label="Confidence" value={safeString(an.confidence_level) || 'Medium'} />
                    <AnalysisRow label="Tone" value={safeString(an.tone) || 'Professional'} />
                    <AnalysisRow label="Energy" value={safeString(an.energy) || 'Moderate'} />
                    <AnalysisRow label="Clarity" value={safeString(an.clarity) || 'Clear'} />
                </div>
                <div className="feedback-section">
                    <div className="feedback-title">👁 Visual</div>
                    <AnalysisRow label="Eye Contact" value={safeString(vis.looking_away_frequency) || 'Good'} />
                    <AnalysisRow label="Confidence" value={safeString(vis.confidence_visual) || 'Medium'} />
                    <AnalysisRow label="Interest" value={safeString(vis.interest_level) || 'Engaged'} />
                    <AnalysisRow label="Fidgeting" value={safeString(vis.fidgeting) || 'Minimal'} />
                </div>
            </div>

            {/* Strengths & Improvements */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div className="feedback-section" style={{ borderLeft: '3px solid #10b981' }}>
                    <div className="feedback-title" style={{ color: '#10b981' }}>✓ Strengths</div>
                    <ul style={{ margin: 0, paddingLeft: '1.25rem', color: '#374151' }}>
                        {strengths.map((s, i) => <li key={i} style={{ marginBottom: '0.5rem' }}>{safeString(s)}</li>)}
                    </ul>
                </div>
                <div className="feedback-section" style={{ borderLeft: '3px solid #f59e0b' }}>
                    <div className="feedback-title" style={{ color: '#f59e0b' }}>⚡ Improve</div>
                    <ul style={{ margin: 0, paddingLeft: '1.25rem', color: '#374151' }}>
                        {improvements.map((s, i) => <li key={i} style={{ marginBottom: '0.5rem' }}>{safeString(s)}</li>)}
                    </ul>
                </div>
            </div>

            {/* Content Feedback */}
            {fb.content_feedback && (
                <div className="feedback-section">
                    <div className="feedback-title">💡 Detailed Feedback</div>
                    <p style={{ color: '#6b7280', lineHeight: '1.7', margin: 0 }}>{safeString(fb.content_feedback)}</p>
                </div>
            )}

            {/* Suggestion */}
            {suggestion && (
                <div className="feedback-section" style={{ background: 'rgba(99,102,241,0.05)', borderLeft: '3px solid #6366f1' }}>
                    <div className="feedback-title" style={{ color: '#6366f1' }}>💬 Try Saying</div>
                    <p style={{ color: '#374151', fontStyle: 'italic', margin: 0 }}>"{suggestion}"</p>
                </div>
            )}

            {/* Follow-up Question - NEW FEATURE */}
            {followUp && (
                <div className="feedback-section" style={{ background: 'rgba(239, 68, 68, 0.05)', borderLeft: '3px solid #ef4444' }}>
                    <div className="feedback-title" style={{ color: '#ef4444' }}>🎯 Likely Follow-up Question</div>
                    <p style={{ color: '#374151', fontWeight: '500', margin: 0 }}>"{followUp}"</p>
                    <p style={{ color: '#6b7280', fontSize: '0.875rem', marginTop: '0.5rem' }}>Prepare for this based on your answer!</p>
                </div>
            )}

            {/* Community */}
            <div className="feedback-section">
                <div className="feedback-title">👥 How Others Answered</div>
                {COMMUNITY.map((r, i) => (
                    <div key={i} style={{ display: 'flex', gap: '1rem', padding: '0.75rem', background: '#f9fafb', borderRadius: '8px', marginBottom: '0.5rem' }}>
                        <div style={{ color: '#6366f1', fontWeight: '600', minWidth: '45px', textAlign: 'center' }}>▲ {r.votes}</div>
                        <p style={{ margin: 0, color: '#374151', fontSize: '0.9rem' }}>"{r.text}"</p>
                    </div>
                ))}
            </div>

            {/* Action Buttons */}
            <div style={{ display: 'flex', gap: '1rem' }}>
                <button
                    onClick={() => downloadPDF(data, question)}
                    className="btn btn-secondary"
                    style={{ flex: 1 }}
                >
                    📥 Download Report
                </button>
                <button onClick={onNext} className="btn btn-primary" style={{ flex: 2 }}>
                    {isLastQuestion ? '🎉 Finish Interview' : 'Next Question →'}
                </button>
            </div>
        </div>
    );
};

const MetricCard = ({ label, value, hint }) => (
    <div className="metric-card">
        <div className="metric-label">{label}</div>
        <div className="metric-value">{value}</div>
        {hint && <div style={{ fontSize: '0.75rem', color: '#9ca3af', marginTop: '0.25rem' }}>{hint}</div>}
    </div>
);

const AnalysisRow = ({ label, value }) => (
    <div style={{ display: 'flex', justifyContent: 'space-between', padding: '0.5rem 0', borderBottom: '1px solid #f3f4f6', fontSize: '0.875rem' }}>
        <span style={{ color: '#6b7280' }}>{label}</span>
        <span style={{ color: '#374151', fontWeight: '500', textTransform: 'capitalize' }}>{String(value)}</span>
    </div>
);

export default AnalysisDashboard;
